apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: usuarios-ingress
  namespace: usuarios
  labels:
    app: usuarios
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: usuarios-usuarios-strip@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /api/usuarios
        pathType: Prefix
        backend:
          service:
            name: usuarios-service
            port:
              number: 80
